### base url
@BASE_URL = http://127.0.0.1:5000

### GET ALL ANIMALS
GET {{BASE_URL}}/animals

### GET ANIMAL BY ID
GET {{BASE_URL}}/animals/1


### POST ANIMAL
POST {{BASE_URL}}/animals
Content-Type: application/json

{
    "age": 12,
    "gender": "male",
    "species": "carnivore"
}

### UPDATE ANIMAL
PUT {{BASE_URL}}/animals/1
Content-Type: application/json

{
    "age": 122,
    "gender": "male",
    "species": "carnivore"
}



### DELETE ANIMAL
DELETE {{BASE_URL}}/animals/1

# ==============================================

### GET ALL EMPLOYEE
GET {{BASE_URL}}/employees

### GET EMPLOYEE BY ID
GET {{BASE_URL}}/employees/1

### POST EMPLOYEE
POST {{BASE_URL}}/employees
Content-Type: application/json

{
    "name": "EMP1",
    "email": "staff@email.com",
    "phone": "0112",
    "role": "staff",
    "schedule": "Monday - Friday"
}

### UPDATE EMPLOYEE
PUT {{BASE_URL}}/employees/1
Content-Type: application/json

{
    "name": "EMP12",
    "email": "staff@email.com",
    "phone": "0112",
    "role": "staff",
    "schedule": "Monday - Friday"
}

### DELETE EMPLOYEE
DELETE {{BASE_URL}}/employees/12