### base url
@BASE_URL = http://127.0.0.1:5000

@JWT_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6dHJ1ZSwiaWF0IjoxNzExMDE5OTI4LCJqdGkiOiIyZTM5MWI0Zi0wZjMwLTQxZDgtOWJhOS1hMTJmN2Y5NDYyOGYiLCJ0eXBlIjoiYWNjZXNzIiwic3ViIjoxLCJuYmYiOjE3MTEwMTk5MjgsImNzcmYiOiI5YzYzZTViOC00OTUwLTRjMmUtYWM3ZC04ODE3ZjRiZGQ2NjUiLCJleHAiOjE3MTEwMjA4Mjh9.PZfVPvwFj_9S-bGnVFWaUIrhgjz6jJ9vVRzVL-aIl34

# USER ==============================================

### POST USER
POST {{BASE_URL}}/users
Content-Type: application/json

{
    "email": "user2@gmail.com",
    "username": "user2",
    "password": "password"
}

### LOGIN USER
POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
    "username": "user2",
    "password": "password"
}

### GET USER
GET {{BASE_URL}}/users/me
Authorization: Bearer {{JWT_TOKEN}}

### UPDATE USER
PUT {{BASE_URL}}/users/me
Authorization: Bearer {{JWT_TOKEN}}
Content-Type: application/json

{
    "email": "user1@gmail.com",
    "username": "user1",
    "password": "password"
}


# ACCOUNT ==============================================

### GET ALL ACCOUNTS OF CURRENT USER
GET {{BASE_URL}}/accounts
Authorization: Bearer {{JWT_TOKEN}}


### GET ACCOUNT BY ID
GET {{BASE_URL}}/accounts/3
Authorization: Bearer {{JWT_TOKEN}}

### POST ACCOUNT
POST {{BASE_URL}}/accounts
Authorization: Bearer {{JWT_TOKEN}}
Content-Type: application/json

{
    "account_type": "savings"
}

### UPDATE ACCOUNT
PUT {{BASE_URL}}/accounts/3
Authorization: Bearer {{JWT_TOKEN}}
Content-Type: application/json

{
    "account_type": "savings"
}

### DELETE ACCOUNT
DELETE {{BASE_URL}}/accounts/2
Authorization: Bearer {{JWT_TOKEN}}

# TRANSACTIONS ==============================================

### GET ALL TRANSACTIONS OF CURRENT USER
GET {{BASE_URL}}/transactions
Authorization: Bearer {{JWT_TOKEN}}

### GET TRANSACTION BY ID
GET {{BASE_URL}}/transactions/1
Authorization: Bearer {{JWT_TOKEN}}

### POST TRANSACTION
POST {{BASE_URL}}/transactions
Authorization: Bearer {{JWT_TOKEN}}
Content-Type: application/json

{
    "to_account_id": 3,
    "from_account_id": 4,
    "amount": 500,
    "type": "transfer",
    "description": "hehe"
}

### POST TRANSACTION
POST {{BASE_URL}}/transactions/withdrawal
Authorization: Bearer {{JWT_TOKEN}}
Content-Type: application/json

{
    "from_account_id": "2",
    "amount": 200,
    "type": "deposit",
    "description": "hehe"
}


### POST TRANSACTION
POST {{BASE_URL}}/transactions/deposit
Authorization: Bearer {{JWT_TOKEN}}
Content-Type: application/json

{
    "to_account_id": "2",
    "amount": 200,
    "type": "deposit",
    "description": "hehe"
}

### POST TRANSACTION
POST {{BASE_URL}}/transactions/transfer
Authorization: Bearer {{JWT_TOKEN}}
Content-Type: application/json

{
    "from_account_id": "2",
    "to_account_id": "1",
    "amount": 2000,
    "type": "deposit",
    "description": "hehe"
}

# AUTH ==============================================

### REGISTER
POST {{BASE_URL}}/auth/register-jwt
Content-Type: application/json

{
    "email": "user3@gmail.com",
    "username": "user3",
    "password_hash": "password"
}

### LOGIN

POST {{BASE_URL}}/auth/login-jwt
Content-Type: application/json

{
    "email": "user3@gmail.com",
    "username": "user3",
    "password_hash": "password"
}